[tool.poetry]
name = "prompt"
version = "0.1.0"
description = ""
authors = ["Farouk Charkas <farouk.charkas@gmail.com>"]
readme = "README.md"
packages = [{include = "../prompt"}]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
